Repository AY2425S2-CS2103-F08-1/tp, pull requests merged in 2025-03, with the labels that each got.

#65 Fix `PersonCard.java` to `CustomerCard.java`
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/customer/Address.java
  src/main/java/seedu/address/model/customer/Email.java
  src/main/java/seedu/address/model/customer/exceptions/CustomerNotFoundException.java
  src/main/java/seedu/address/model/customer/exceptions/DuplicateCustomerException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/CustomerListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#68 Adding delete command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.High

#67 Branch create reservation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/customer/DateTime.java
  src/main/java/seedu/address/model/customer/Diners.java
  src/main/java/seedu/address/model/customer/Name.java
  src/main/java/seedu/address/model/customer/Phone.java
  src/main/java/seedu/address/model/customer/UniqueCustomerList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/resources/view/CustomerListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidCustomerAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
  src/test/java/seedu/address/model/customer/DateTimeTest.java
  src/test/java/seedu/address/model/customer/DinersTest.java
  src/test/java/seedu/address/model/customer/NameTest.java
  src/test/java/seedu/address/model/customer/UniqueCustomerListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/testutil/CustomerBuilder.java
  src/test/java/seedu/address/testutil/CustomerUtil.java
  src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
Labels: priority.High

#69 Add show command
  README.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
Labels: priority.High

#79 Cut `Address` from `Customer` along with all dependencies
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/logic/commands/FindCommand.java
  src/main/java/seedu/reserve/logic/parser/AddCommandParser.java
  src/main/java/seedu/reserve/logic/parser/CliSyntax.java
  src/main/java/seedu/reserve/logic/parser/EditCommandParser.java
  src/main/java/seedu/reserve/logic/parser/ParserUtil.java
  src/main/java/seedu/reserve/model/customer/Address.java
  src/main/java/seedu/reserve/model/customer/Customer.java
  src/main/java/seedu/reserve/model/customer/Diners.java
  src/main/java/seedu/reserve/model/customer/Name.java
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
  src/main/java/seedu/reserve/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/reserve/ui/CustomerCard.java
  src/main/resources/view/CustomerListCard.fxml
  src/test/data/JsonReserveMateStorageTest/invalidAndValidCustomerReserveMate.json
  src/test/data/JsonReserveMateStorageTest/invalidCustomerReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/duplicateCustomerReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/invalidCustomerReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/typicalCustomersReserveMate.json
  src/test/java/seedu/reserve/logic/LogicManagerTest.java
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/reserve/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/model/ReserveMateTest.java
  src/test/java/seedu/reserve/model/customer/AddressTest.java
  src/test/java/seedu/reserve/model/customer/CustomerTest.java
  src/test/java/seedu/reserve/model/customer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/reserve/model/customer/UniqueCustomerListTest.java
  src/test/java/seedu/reserve/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/reserve/testutil/CustomerBuilder.java
  src/test/java/seedu/reserve/testutil/CustomerUtil.java
  src/test/java/seedu/reserve/testutil/EditCustomerDescriptorBuilder.java
  src/test/java/seedu/reserve/testutil/TypicalCustomers.java
Labels: type.Task, priority.Medium

#85 Add FindCommandParser test cases
  src/test/java/seedu/reserve/logic/parser/FindCommandParserTest.java
Labels: type.Task

#91 Update parser to case insensitive
  src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java
  src/test/java/seedu/reserve/logic/parser/ReserveMateParserTest.java
Labels: priority.High

#94 Fix List command bug and update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/ListCommand.java
  src/test/java/seedu/reserve/logic/LogicManagerTest.java
  src/test/java/seedu/reserve/logic/commands/ListCommandTest.java
Labels: type.Story, type.Bug

#97 Fix list bug
  src/main/java/seedu/reserve/logic/commands/ListCommand.java
Labels: type.Bug

#98 Add tests
  src/test/java/seedu/reserve/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/reserve/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#100 Update guides
  README.md
  docs/UserGuide.md
  docs/images/deleteCommandResult.png
Labels: priority.Medium

#104 Rename customer tests
  src/test/java/seedu/reserve/commons/core/index/IndexTest.java
  src/test/java/seedu/reserve/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/FindCommandTest.java
  src/test/java/seedu/reserve/logic/commands/ListCommandTest.java
  src/test/java/seedu/reserve/logic/commands/ShowCommandTest.java
  src/test/java/seedu/reserve/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/logic/parser/ReserveMateParserTest.java
  src/test/java/seedu/reserve/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/reserve/model/ModelManagerTest.java
  src/test/java/seedu/reserve/model/ReserveMateTest.java
  src/test/java/seedu/reserve/model/reservation/UniqueReservationListTest.java
  src/test/java/seedu/reserve/storage/JsonAdaptedReservationTest.java
  src/test/java/seedu/reserve/storage/JsonSerializableReserveMateTest.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
  src/test/java/seedu/reserve/testutil/ReservationUtil.java
  src/test/java/seedu/reserve/testutil/ReserveMateBuilder.java
  src/test/java/seedu/reserve/testutil/TestUtil.java
  src/test/java/seedu/reserve/testutil/TypicalIndexes.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: type.Task

#102 Fix bug when read date input from `reservemate.json` file
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/model/reservation/DateTime.java
  src/main/java/seedu/reserve/storage/JsonAdaptedReservation.java
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/model/reservation/DateTimeTest.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: type.Bug, priority.Medium

#107 Update Ui.png and change title
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#108 Edit user guide, developer guide and readME
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#105 Add phone constraints
  src/main/java/seedu/reserve/model/reservation/Phone.java
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/model/reservation/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/reserve/model/reservation/PhoneTest.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: priority.High

#109 Update README,UG,DG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Story, type.Task

#112 Add edit, clear, exit in README
  README.md
  docs/UserGuide.md
Labels: type.Task

#122 Add sorting by date-time and reschedule reservation
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/editCommandResult.png
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/model/reservation/DateTime.java
  src/main/java/seedu/reserve/model/reservation/UniqueReservationList.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/FindCommandTest.java
  src/test/java/seedu/reserve/model/reservation/UniqueReservationListTest.java
Labels: type.Enhancement, priority.Medium

#141 Update PaserClasses.puml to include ReserveMate
  docs/diagrams/ParserClasses.puml
Labels: type.Story

#136 Add max booking time constraint
  README.md
  docs/UserGuide.md
  src/main/java/seedu/reserve/model/reservation/DateTime.java
  src/test/data/JsonReserveMateStorageTest/invalidAndValidReservationReserveMate.json
  src/test/data/JsonReserveMateStorageTest/invalidReservationReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/duplicateReservationReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/invalidReservationReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/FindCommandTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/model/reservation/DateTimeTest.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: priority.High

#142 Update sequence diagram
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task

#146 Implement view all free time slots feature
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/commands/FreeCommand.java
  src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java
  src/test/java/seedu/reserve/logic/commands/FreeCommandTest.java
Labels: type.Enhancement, priority.Medium

#147 Update BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task

#148 Implement customer preferences
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/savePreferenceCommand.png
  docs/images/showPreferenceCommand.png
  src/main/java/seedu/reserve/logic/commands/HelpCommand.java
  src/main/java/seedu/reserve/logic/commands/PreferenceCommand.java
  src/main/java/seedu/reserve/logic/parser/PreferenceParser.java
  src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java
  src/main/java/seedu/reserve/model/reservation/Reservation.java
  src/test/java/seedu/reserve/logic/commands/PreferenceCommandTest.java
  src/test/java/seedu/reserve/logic/parser/PreferenceCommandParserTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationPreferenceTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationTest.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
Labels: priority.Medium

#160 Fix sample data bug to allow for any valid date time
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
  src/test/java/seedu/reserve/testutil/SampleDataUtilTest.java
Labels: type.Task, type.Bug

#196 Update UML Diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#198 Fix make command case insensitive
  src/main/java/seedu/reserve/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
Labels: type.Bug

#197 Fix duplicate reservation with customers with the same name
  src/main/java/seedu/reserve/model/reservation/Name.java
  src/test/java/seedu/reserve/model/reservation/NameTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationTest.java
Labels: type.Bug

#199 Fix space issue for phone number
  src/main/java/seedu/reserve/model/reservation/Phone.java
  src/test/java/seedu/reserve/model/reservation/PhoneTest.java
Labels: type.Bug

#200 Fix leading zeros bug in `Diner` class
  src/main/java/seedu/reserve/model/reservation/Diners.java
  src/test/java/seedu/reserve/model/reservation/DinersTest.java
Labels: type.Bug

#213 Fix ClearCommand message issue
  src/main/java/seedu/reserve/logic/commands/ClearCommand.java
Labels: severity.Low

#210 Fix email regex validation
  src/main/java/seedu/reserve/model/reservation/Email.java
  src/test/java/seedu/reserve/model/reservation/EmailTest.java
Labels: type.Bug, severity.Medium

#215 Edit command bugs
  src/main/java/seedu/reserve/commons/util/StringUtil.java
  src/main/java/seedu/reserve/logic/parser/EditCommandParser.java
  src/main/java/seedu/reserve/model/reservation/Email.java
  src/test/java/seedu/reserve/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/reserve/model/reservation/EmailTest.java
Labels: alpha-bug

#214 Fix DeleteCommand format issue
  src/main/java/seedu/reserve/logic/commands/DeleteCommand.java
  src/test/java/seedu/reserve/logic/commands/DeleteCommandTest.java
Labels: severity.Low

#221 Enhance GUI Layout and Text Display
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/logic/commands/ClearCommand.java
  src/main/java/seedu/reserve/logic/commands/DeleteCommand.java
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/logic/commands/ExitCommand.java
  src/main/java/seedu/reserve/logic/commands/FilterCommand.java
  src/main/java/seedu/reserve/logic/commands/FindCommand.java
  src/main/java/seedu/reserve/logic/commands/HelpCommand.java
  src/main/java/seedu/reserve/logic/commands/ListCommand.java
  src/main/java/seedu/reserve/logic/commands/PreferenceCommand.java
  src/main/java/seedu/reserve/logic/commands/ShowCommand.java
  src/main/java/seedu/reserve/ui/MainWindow.java
  src/main/java/seedu/reserve/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, type.Task

#222 Branch bug duplicate reservation
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/model/reservation/Reservation.java
  src/test/java/seedu/reserve/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationTest.java
Labels: type.Bug, severity.High, alpha-bug

#223 Fix one word limitation in occasion
  config/checkstyle/checkstyle.xml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/logic/parser/AddCommandParser.java
  src/main/java/seedu/reserve/logic/parser/EditCommandParser.java
  src/main/java/seedu/reserve/logic/parser/ParserUtil.java
  src/main/java/seedu/reserve/model/occasion/Occasion.java
  src/main/java/seedu/reserve/model/reservation/Reservation.java
  src/main/java/seedu/reserve/model/tag/Tag.java
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
  src/main/java/seedu/reserve/storage/JsonAdaptedOccasion.java
  src/main/java/seedu/reserve/storage/JsonAdaptedReservation.java
  src/main/java/seedu/reserve/storage/JsonAdaptedTag.java
  src/main/resources/view/ReservationListCard.fxml
  src/test/java/seedu/reserve/logic/LogicManagerTest.java
  src/test/java/seedu/reserve/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/EditReservationDescriptorTest.java
  src/test/java/seedu/reserve/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/model/ReserveMateTest.java
  src/test/java/seedu/reserve/model/occasion/OccasionTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationPreferenceTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationTest.java
  src/test/java/seedu/reserve/model/reservation/UniqueReservationListTest.java
  src/test/java/seedu/reserve/model/tag/TagTest.java
  src/test/java/seedu/reserve/storage/JsonAdaptedReservationTest.java
  src/test/java/seedu/reserve/testutil/EditReservationDescriptorBuilder.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
  src/test/java/seedu/reserve/testutil/ReservationUtil.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: severity.High, alpha-bug

#225 Help Command - Extra Parameters no longer allowed
  src/main/java/seedu/reserve/logic/commands/CommandResult.java
  src/main/java/seedu/reserve/logic/commands/HelpCommand.java
  src/main/java/seedu/reserve/logic/parser/HelpCommandParser.java
  src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java
  src/main/java/seedu/reserve/ui/MainWindow.java
  src/test/java/seedu/reserve/logic/LogicManagerTest.java
  src/test/java/seedu/reserve/logic/commands/CommandResultTest.java
  src/test/java/seedu/reserve/logic/commands/HelpCommandTest.java
  src/test/java/seedu/reserve/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/ReserveMateParserTest.java
Labels: severity.Medium, alpha-bug

#226 Fix JSON occasion read in
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
  src/main/java/seedu/reserve/storage/JsonAdaptedReservation.java
  src/test/data/JsonSerializableReserveMateTest/duplicateReservationReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationTest.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: priority.Medium, alpha-bug

#227 Fix preference command unable to save
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/logic/commands/PreferenceCommand.java
  src/main/java/seedu/reserve/logic/parser/PreferenceParser.java
  src/main/java/seedu/reserve/model/ModelManager.java
  src/main/java/seedu/reserve/model/reservation/Preference.java
  src/main/java/seedu/reserve/model/reservation/Reservation.java
  src/main/java/seedu/reserve/storage/JsonAdaptedReservation.java
  src/test/data/JsonSerializableReserveMateTest/duplicateReservationReserveMate.json
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/EditReservationDescriptorTest.java
  src/test/java/seedu/reserve/logic/commands/PreferenceCommandTest.java
  src/test/java/seedu/reserve/logic/parser/PreferenceCommandParserTest.java
  src/test/java/seedu/reserve/model/reservation/ReservationPreferenceTest.java
  src/test/java/seedu/reserve/storage/JsonAdaptedReservationTest.java
  src/test/java/seedu/reserve/testutil/ReservationBuilder.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: priority.High, alpha-bug
