Repository AY2425S2-CS2103-F08-1/tp, pull requests merged in 2025-04, with the labels that each got.

#229 Update project docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Story, priority.Low

#235 Date time issues
  docs/UserGuide.md
  src/main/java/seedu/reserve/model/reservation/DateTime.java
  src/test/java/seedu/reserve/logic/commands/CommandTestUtil.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/commands/FilterCommandTest.java
  src/test/java/seedu/reserve/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/model/reservation/DateTimeTest.java
  src/test/java/seedu/reserve/model/reservation/UniqueReservationListTest.java
Labels: severity.Medium

#232 Fix occasion
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/commands/AddCommand.java
  src/main/java/seedu/reserve/model/occasion/Occasion.java
  src/test/java/seedu/reserve/logic/commands/AddCommandTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
Labels: severity.Medium

#236 Remove pref show command
  README.md
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/Messages.java
  src/main/java/seedu/reserve/logic/commands/PreferenceCommand.java
  src/main/java/seedu/reserve/logic/parser/ParserUtil.java
  src/main/java/seedu/reserve/logic/parser/PreferenceParser.java
  src/test/java/seedu/reserve/logic/commands/PreferenceCommandTest.java
  src/test/java/seedu/reserve/logic/parser/PreferenceCommandParserTest.java
Labels: alpha-bug

#243 Update sample date-time to be dynamic w.r.t current time
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
Labels: type.Task, severity.Medium

#240 Developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UIClassDiagram.png
Labels: type.Task

#253 Fix DeleteCommand error message
  src/main/java/seedu/reserve/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/reserve/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, severity.Low, alpha-bug

#254 Developer guide
  docs/DeveloperGuide.md
Labels: type.Story, type.Task

#257 Branch remove edit constraint
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/main/java/seedu/reserve/logic/parser/EditCommandParser.java
  src/main/java/seedu/reserve/logic/parser/ParserUtil.java
  src/main/java/seedu/reserve/model/reservation/Email.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
  src/test/java/seedu/reserve/logic/parser/ParserUtilTest.java
  src/test/java/seedu/reserve/testutil/EditReservationDescriptorBuilder.java
Labels: type.Enhancement, priority.Medium

#259 Add preference in SampleDataUtil
  src/main/java/seedu/reserve/model/util/SampleDataUtil.java
Labels: type.Task

#262 Fix UserGuide Image
  docs/UserGuide.md
Labels: type.Task

#268 Update pref formatting in UG
  docs/UserGuide.md
Labels: type.Task

#267 Branch duplicate bug
  src/main/java/seedu/reserve/logic/commands/EditCommand.java
  src/test/java/seedu/reserve/logic/commands/EditCommandTest.java
Labels: priority.High, severity.High, alpha-bug

#317 Update the date time for test data to be within 60 days
  src/test/data/JsonSerializableReserveMateTest/typicalReservationReserveMate.json
  src/test/java/seedu/reserve/logic/commands/FilterCommandTest.java
  src/test/java/seedu/reserve/logic/commands/FindCommandTest.java
  src/test/java/seedu/reserve/testutil/TypicalReservation.java
Labels: severity.Low

#318 Update UG and User Guide
  docs/UserGuide.md
  src/main/java/seedu/reserve/ui/HelpWindow.java
Labels: type.Bug

#320 Update DG and Help List
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/reserve/logic/commands/HelpCommand.java
  src/main/java/seedu/reserve/ui/StatisticsWindow.java
Labels: type.Bug

#324 Developer guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Task
